#######################################################
# *********** System env ***********
#######################################################
sys:
  env:
    cd: L

# EAI \uC2DC\uC2A4\uD15C \uD658\uACBD \uCF54\uB4DC (D:\uAC1C\uBC1C, P:\uC6B4\uC601, L:\uB85C\uCEEC)
eai:
  sys:
    env:
      cd: L

server:
  port: 5001
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      force-response: true

#######################################################
# *********** crypt key ***********
#######################################################
app:
  enckey: ENC(wR5/TCUi4RxoN7ctYEOEqLQElXbdusMeKE1Z9+R4mil8TaW+tcPDB4RWIPOT9ZqkwHaFrS19/ECyh5TzcgLMjQ==)


#######################################################
# *********** pid3 ***********
#######################################################
spring:
  main:
    allow-bean-definition-overriding: true  # 빈 오버라이드 허용
  pid:
    file: C:/bwc-ide/workspace/messeage-gate/msggate.pid

  #######################################################
  # *********** datasource settings ***********
  #######################################################
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  # 멀티 데이터소스 설정 (현재 비활성화)
  # ma-datasource:
  #   datasource:
  #     hikari:
  #       driver-class-name: org.h2.Driver
  #       jdbc-url: jdbc:h2:mem:ma-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #       username: sa
  #       password: 
  #       connection-test-query: SELECT 1
  #       minimum-idle: 1
  #       maximum-pool-size: 5

  #######################################################
  # *********** JPA settings ***********
  #######################################################
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

#######################################################
# *********** hikari logging ***********
# configuration 정보가 필요한 경우만 DEBUG로 변경
#######################################################
logging:
  config: classpath:logback-local.xml  # 로컬용 로깅 설정 사용
  level:
    root: INFO
    com.bwc: DEBUG
